// import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";
// import styles from "./index.module.css";
import styles from "~/styles/styles.module.css"
import { boolean } from "zod";
import { useState } from "react";

export default function Home() {
  // const hello = api.post.hello.useQuery({ text: "from tRPC" });

  // const [buttonWasClicked, setButtonWasClicked] = useState(false);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>


{/* ===================================================== */}




{/* HMaking a new comment */}



{/* ===================================================== */}





        <div className={styles.container}>
          <h1 className={styles.title}>
          Surely Tech
          </h1>
          <div className={styles.cardRow}>




{/* = ======================================================= */}





{/* ctrl + c (copy)
ctrl + x (cut)
ctrl + v (paste) */}











{/* <button onClick={() => setButtonWasClicked(prevState => !prevState)}>
  Click me
</button> */}



{/* 
{buttonWasClicked == true ? (

): <div></div>} */}




            <Link
              className={styles.card}
              href="/homePage"
              >


              <h3 className={styles.cardTitle}>Donavon</h3>




            </Link>

            <Link
              className={styles.card}
              href="/arno"
              >


              <h3 className={styles.cardTitle}>Arno →</h3>




            </Link>


          


            {/* = ======================================================= */}




          </div>
         
        </div>

        {/* ================================================================================================ */}


















        {/* ================================================================================================ */}
      </main>
    </>
  );
}

// Please remove the below authentication code (Arno)

// function AuthShowcase() {
//   const { data: sessionData } = useSession();

//   const { data: secretMessage } = api.post.getSecretMessage.useQuery(
//     undefined, // no input
//     { enabled: sessionData?.user !== undefined }
//   );

//   return (
//     <div className={styles.authContainer}>
//       <p className={styles.showcaseText}>
//         {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
//         {secretMessage && <span> - {secretMessage}</span>}
//       </p>
//       <button
//         className={styles.loginButton}
//         onClick={sessionData ? () => void signOut() : () => void signIn()}
//       >
//         {sessionData ? "Sign out" : "Sign in"}
//       </button>
//     </div>
//   );
// }
